kind: Deployment
apiVersion: apps/v1
metadata:
   name: mydemodeployments
spec:
   replicas: 3
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     name: deploy
   template:
     metadata:
       name: testpod1
       labels:
         name: deploy
     spec:
      containers:
        - name: c00
          image: http
   #       command: ["/bin/bash","-c", while true; do echo Hello All; sleep 5; done]
          ports:
          - containerPort: 80
#      volumes:
 #     - name: my-persistent-storage
 #       persistentVolumeClaim:
 #         claimName: my-pv-claim
