kind: Deployment
apiVersion: apps/v1
metadata:
   name: mydemodeployments
   namespace: my-psp-ns
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     name: deploy
   template:
     metadata:
       name: testpod1
       labels:
         name: deploy
     spec:
      containers:
        - name: c00
          image: httpd
          ports:
          - containerPort: 80
