apiVersion: v1
kind: PersistentVolume
metadata: 
  name: my-pv
  namespace: demo-namespace
spec:
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    fsType: gp2
    volumeID: vol-03799839096f198bf
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
